apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-fdb-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-fdb-5.3.6+20260625.161841.7-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/fdb-operator-catalog@sha256:64fc528a89808523974227f480bdc10d420247981916eb69c59c89b9f9e7c723
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
