apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-data-product-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-data-product-5.4.1+20260610.085151.1017-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-data-product-operator-catalog@sha256:c52842d1d974722193154e2dc6a5d57feae9022884925f7e1c3bd582194e2b87
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
