kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-cdws/cdws:6.4.0.10_iFix00-2026-08-20@sha256:049a8b0ea3790550eda46abd460432d27ac0e5e50129c88c9cfac625fbcb382b
