apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cp-waiops-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cp-waiops-1.19.0
  publisher: IBM
  image: icr.io/cpopen/ibm-cp-waiops-case-bundle-catalog@sha256:21bdf93da13e1d07508cba2e2e2aec941b780c35e8ade6da0d1aaa1bec3b5610
  sourceType: grpc
