apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-redis-cp-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-redis-cp-1.3.2+20260723.205508.738
  publisher: IBM
  image: icr.io/cpopen/ibm-redis-cp-operator-catalog@sha256:f7c1354005de9eb996963d68d2971c911151ce27997c45042d84dbe57f224960
  sourceType: grpc
