apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-oms-pro-case-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-oms-pro-case-3.0.42-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-oms-pro-case-catalog@sha256:18a745a36f9d603ba2dbb13250c2197fb5b7159585baac6115b281e47f6c5106
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
