apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-oms-pro-case-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-oms-pro-case-3.0.39-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-oms-pro-case-catalog@sha256:42b7251bb8020d064ffc54faeed42c6f1d0e25ddffc8444c9a8e2d97ebec733a
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
