apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-watson-assistant-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-watson-assistant-5.16.0+20260811.195549.4346
  publisher: IBM
  image: icr.io/cpopen/ibm-watson-assistant-operator-catalog@sha256:b165de97715df8947d2e0c9d08be613353598a671cd76e009be883be0f6f645b
  sourceType: grpc
