apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-eventstreams
  namespace: openshift-marketplace
spec:
  displayName: ibm-eventstreams-13.0.1
  publisher: IBM
  image: icr.io/cpopen/ibm-eventstreams-catalog@sha256:736ad9608e888a0d1a27a250ebe53ae052f991cf0fc53352ac9f40311d211019
  sourceType: grpc
