apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cloud-native-postgresql-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cloud-native-postgresql-5.31.2+20260723.134905.2735
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog@sha256:ea0fbd0c9e6bc75c085af3db5cfe8268760953f193a9241b91f97a010644dae6
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-zen-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-zen-6.4.11+20260727.234054.6
  publisher: IBM
  image: icr.io/cpopen/ibm-zen-operator-catalog@sha256:9c4c2e23ae1c23fcbf587bdbbd0b0ad015676d96b1c0f05731889dfbdc98dfef
  sourceType: grpc
