apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-dp-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-dp-12.0.6+20260815.003343.6004-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-dp-operator-catalog@sha256:bc5e01a818b4ebe06be655aebcc94e1d58b4d158f4bee4240f45de7dd386d9e3
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
