apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cpd-platform
  namespace: openshift-marketplace
spec:
  displayName: ibm-cp-datacore-5.10.5+20260812.152707.1841.6105.7
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-platform-operator-catalog@sha256:0011fae3b2e003a6717522d22bd609f4a57518d54ef464ac27c91c8c29800ec7
  sourceType: grpc
