kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-ssp-engine/ssp-engine-docker-image:6.2.2.0-iFix00-2026-09-10@sha256:8c65d0b79dd7be1d9eaf7bc0ca9cb25a0242f6ae0cbcb26db6ba21fa64ae7c2e
