kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  operators:
  - catalog: icr.io/cpopen/isf-operator-software-catalog@sha256:f6a5ce639fb3fa004fec537b1813b97e5def0c08e0d66b0188129394d14242e7
    packages:
    - name: isf-operator
      channels:
      - name: v2.0
    full: true
  additionalImages:
  - name: icr.io/cpopen/isf-operator-software-catalog:v2.12.2@sha256:f6a5ce639fb3fa004fec537b1813b97e5def0c08e0d66b0188129394d14242e7
