apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-watson-aiops-ui-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-watson-aiops-ui-operator-case-1.19.0
  publisher: IBM
  image: icr.io/cpopen/ibm-watson-aiops-ui-catalog@sha256:dba60d62f5ca13c471897a18594888f9077e1e246c19484fdc64b490cf23a2e1
  sourceType: grpc
