apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-mdm-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-mdm-4.11.1+20260312.150530.27-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/mdm-operator-catalog@sha256:24e2d41df5bcc7beafde242ab55934abaf13c3bde35bb046a511b84ffc7ca1cf
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
