apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-planning-analytics-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-planning-analytics-5.4.3+20260720.154232.2589-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-planning-analytics-operator-catalog@sha256:8617e13b67d1163b7c26c5fef3ad0f89ebbb36f229b7f42786ad2a4201aa210e
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
