apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-hadoop-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-hadoop-5.3.7+20260922.000000.60
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-hadoop-operator-catalog@sha256:e04b31a77b3e40cbdabd4ac90962b429bcab94d2aa65ec405f0ed5ea52c2678a
  sourceType: grpc
