apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-datastage-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-datastage-11.1.8+20260710.074829.7
  publisher: IBM
  image: icr.io/cpopen/ds-operator-catalog@sha256:288bbafca9d3403b7cfa29200005d1bdc355e9990c83531194dff9231a71a702
  sourceType: grpc
