kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  operators:
  - catalog: icr.io/cpopen/ibm-cs-install-catalog@sha256:7e04eb94c33ca06ce1144a5b2ef5cd6bb53ed24b15e68c9414d284826468f9a4
    packages:
    - name: ibm-common-service-operator
      channels:
      - name: v4.19
    - name: ibm-namespace-scope-operator
      channels:
      - name: v4.3
    - name: ibm-odlm
      channels:
      - name: v4.5
    full: true
  additionalImages:
  - name: icr.io/cpopen/ibm-cs-install-catalog:cd-20260730-1213@sha256:7e04eb94c33ca06ce1144a5b2ef5cd6bb53ed24b15e68c9414d284826468f9a4
