apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-dmc-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-dmc-8.12.2+20260713.071929.93
  publisher: IBM
  image: icr.io/cpopen/ibm-dmc-operator-catalog@sha256:a05d157d51295bd3fcd2eb0474bc99276c2808a868ba585c7f413b13a20ec466
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-redis-cp-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-redis-cp-1.4.0+20260609.131456.726
  publisher: IBM
  image: icr.io/cpopen/ibm-redis-cp-operator-catalog@sha256:8391c3e193e9dc54f1a91996daaaca73126d5a814dd82cd49651576a4ac633e9
  sourceType: grpc
