kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  operators:
  - catalog: icr.io/cpopen/ibm-usage-metering-operator-catalog@sha256:23faf774b1a93fb11feace158508fbf714afde253e02232c702eecc5c56cc010
    packages:
    - name: ibm-usage-metering-operator
      channels:
      - name: v1.0
    full: true
  additionalImages:
  - name: icr.io/cpopen/cpfs/cpfs-utils:4.6.23@sha256:050fc75fb194be6bbb5b7ede5349c701717a9590427f081382d1ceb058c73163
  - name: icr.io/cpopen/ibm-usage-metering-operator-catalog:cd-20260723-1016@sha256:23faf774b1a93fb11feace158508fbf714afde253e02232c702eecc5c56cc010
