apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ae-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-analyticsengine-0.0.7
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-analyticsengine-operator-catalog@sha256:72f3c8f00c8f618d278a916efa28a62ab4175b0fa14e036268a93ad6a84f379e
  sourceType: grpc
