apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-baw-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cs-bawautomation-2.7.9
  publisher: IBM
  image: icr.io/cpopen/ibm-cs-bawautomation-catalog@sha256:b028b041a2c4c1eacfee016ac356d4c726fa383646db5f15d0a9fc94866ffd37
  sourceType: grpc
