apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-db2oltp-cp4d-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-db2oltp-5.3.3+20260421.190117.3792.5088
  publisher: IBM
  image: icr.io/cpopen/ibm-db2oltp-cp4d-operator-catalog@sha256:e1dbdbe61a5a3d22fd0b6a5fdc2c30d33ed61ed72702828b142fbfe1ca5003c3
  sourceType: grpc
