apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-wkc-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-wkc-5.4.0+20260610.083013.233
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-wkc-operator-catalog@sha256:89474a87da298ec04580f72db7be91dc06dfbd7b49f873ddcc807b7a5bcae061
  sourceType: grpc
