apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: manta-adl-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: mantaflow-2.5.1+20260609.013334.57-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/manta-adl-operator-catalog@sha256:c6b34c1f92b83d60694aaf950482b22f27903ab2484973bb21ee1f7a91ca2306
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
