apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ccs-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-ccs-12.1.1+20260312.012535.47
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-ccs-operator-catalog@sha256:f70f047e93d6f7bb77f638e5eb6a996895e0b50d5bab05094459fdaab7110c52
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-hadoop-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-hadoop-5.3.2+20260323.000000.26
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-hadoop-operator-catalog@sha256:4355199bc8e84cfbb40a011ce32dade56b74594b7961bd5f19c9f5cbdeff37b7
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ws-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-wsl-8.3.0+20240209.173620.31
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-ws-operator-catalog@sha256:dcac02b3a2490536a39cdd91a2771080eaa1839fc433a506c33804b36778fb05
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-opensearch-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-opensearch-operator-1.2.0
  publisher: IBM
  image: icr.io/cpopen/opencontent-ibm-opensearch-operator-catalog@sha256:c20414136174ef24513560ca56204787fb4a3c3de8f84a490551dd63efb67a7f
  sourceType: grpc
