kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-ssp-cm/ssp-cm-docker-image:6.1.0.4-iFix01-2026-07-22@sha256:8a8f315b663ac8ef7b7dbe72c23bb061e55ce7e5c41fa78d2af6b6a9ba4c257d
