apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ccs-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-ccs-12.1.6+20260520.232601.47
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-ccs-operator-catalog@sha256:bdfec41fee316c05970145e1b3fd1f1295e4f5c027717d04b985cc57f3bea845
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-datastage-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-datastage-enterprise-12.0.0+20260514.074135.234
  publisher: IBM
  image: icr.io/cpopen/ds-operator-catalog@sha256:4b2aa82914b72c0cd91da2032d80a7a4d6ed5fbd5dc2f9d438d5c21b4ab476a6
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-opensearch-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-opensearch-operator-1.4.3
  publisher: IBM
  image: icr.io/cpopen/opencontent-ibm-opensearch-operator-catalog@sha256:4a40ac23337e129531396e2e59bc00f65f25b8b70d52a190d4c116135ff39267
  sourceType: grpc
