kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-cdws/cdws:6.4.0.8_iFix01-2026-06-22@sha256:8db2ca043ab14398ecbe2715b895c1aa2683ca877acf6dee575da3483a104c03
