apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-baw-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cs-bawautomation-2.7.10
  publisher: IBM
  image: icr.io/cpopen/ibm-cs-bawautomation-catalog@sha256:7c3880b6368229a242950bd16f83d9445917b74e54790b6431a18b715115af13
  sourceType: grpc
