apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-baw-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cs-bawautomation-2.8.9
  publisher: IBM
  image: icr.io/cpopen/ibm-cs-bawautomation-catalog@sha256:ae79c64912a02d45efcdd9ec350479d4281c25c780f42d5c8cdd59fd966c137f
  sourceType: grpc
