apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-dpra-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-dpra-1.21.0+20260508.154505.503-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-dpra-operator-catalog@sha256:cfb3eff6f87c375375f0b918a374993bd640935c1fe3cbd71e695b74eafb57dc
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
