apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-oms-pro-case-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-oms-pro-case-3.0.37-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-oms-pro-case-catalog@sha256:351340005dab60a5bcb53f179ff9e0cbc21bd9781891ccf5238cf5be48afecf7
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
