kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  operators:
  - catalog: icr.io/cpopen/ibm-cert-manager-operator-catalog@sha256:435b47b0441486d80c06c5cea6f2182367bc5bcedd2fb92bda24b3be9887e020
    packages:
    - name: ibm-cert-manager-operator
      channels:
      - name: v4.2
    full: true
  additionalImages:
  - name: icr.io/cpopen/cpfs/cpfs-utils:4.6.23@sha256:050fc75fb194be6bbb5b7ede5349c701717a9590427f081382d1ceb058c73163
  - name: icr.io/cpopen/ibm-cert-manager-operator-catalog:cd-20260722-1319@sha256:435b47b0441486d80c06c5cea6f2182367bc5bcedd2fb92bda24b3be9887e020
