apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-knowledge-catalog-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-knowledge-catalog-5.4.4+20260721.203047.4005-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-knowledge-catalog-operator-catalog@sha256:aa555ab873093e929a595acd5a8c019d80ad1d1d1384e881df42dcc3140e8d94
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
