apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-content-assistant-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-content-assistant-1.2.1
  publisher: IBM
  image: icr.io/cpopen/ibm-content-assistant-catalog@sha256:0c12298504f6fe1c70b87216249a4b38911d3bc1eb08ef08503ac86eb973438c
  sourceType: grpc
