apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-storage-fusion-df-case-bundle-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-storage-fusion-df-case-bundle-10.13.0
  publisher: IBM
  image: icr.io/cpopen/isf-data-foundation-catalog@sha256:9a1a640cc9cd105e874a77d81753a23808740350d5fed0959c1a617691d32c60
  sourceType: grpc
