apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-oms-pro-case-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-oms-pro-case-3.0.44-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-oms-pro-case-catalog@sha256:4f5294128fd0bdbb2f3393b62104e0f8f422fdad11c4c9dfd207e724c1f912bb
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
