apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-infrastructure-automation-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-ia-installer-2.0.2
  publisher: IBM
  image: icr.io/cpopen/ibm-infrastructure-automation-operator-catalog@sha256:12ee83b2b560494b151caac12087837e577443f278f721c671936d6bdc6432f2
  sourceType: grpc
