apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-oms-ent-case-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-oms-ent-case-3.0.43-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-oms-ent-case-catalog@sha256:8a6f681abec6b796b475d8383caffe2338b462a4dd5b840c0ecf3db237bbcb9e
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-oms-ent-case-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-oms-ent-case-3.0.43-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-oms-gateway-operator-catalog@sha256:76c07124847f6a71cc571a63f7767a0a94a432b4cbe721c7e12fa867f24fc4da
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-oms-ent-case-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-oms-ent-case-3.0.43-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-oms-sip-operator-catalog@sha256:8bd41e4b0ff7c4f60f31a374ddcb6d49460bd4bb00da3a6746e41c598410a13d
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
