apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ccs-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-ccs-12.1.1+20260312.012535.47
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-ccs-operator-catalog@sha256:f70f047e93d6f7bb77f638e5eb6a996895e0b50d5bab05094459fdaab7110c52
  sourceType: grpc
