apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-bigsql-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-bigsql-case-15.1.0+20260707.090046.13-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-bigsql-operator-catalog@sha256:c97d75844216463918c43d08eb8b69c0652dfb2f6927deba38ff4a6a76cb94aa
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
