apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cloud-native-postgresql-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cloud-native-postgresql-5.31.1+20260310.150029.2714
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog@sha256:79042063952ee9683c972a83ebfa9085f8899ea73403ff7a0de74e537d7b84b3
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cpd-platform
  namespace: openshift-marketplace
spec:
  displayName: ibm-cp-datacore-5.4.2+20260414.141019.1204.642.6
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-platform-operator-catalog@sha256:84bd93d08996b1ac624e0432b2a3f6fcce30cbd490ffc95b7016bcc11b692652
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ae-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-analyticsengine-12.1.1+20260311.091138.1743
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-analyticsengine-operator-catalog@sha256:f9e39aaca082a6ee1b517ff6b2979dc0c36f625b44e029909f09636b8729819f
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ccs-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-ccs-8.1.0
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-ccs-operator-catalog@sha256:4bd21976ae4986a0d644fcbb5d804f2a01cf202076c83d768c74d437352cc73b
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ccs-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-ccs-12.1.2+20260402.132309.66
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-ccs-operator-catalog@sha256:42b114e735f3d0501c3ada562866bcde68d6111a2e853c028cf7d4be1ef6ef5d
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-datastage-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-datastage-enterprise-11.1.0+20260220.064525.100
  publisher: IBM
  image: icr.io/cpopen/ds-operator-catalog@sha256:d14f94246c4aaf8cecf0ddf6586e739dba32e29767c5209865ad2a3d303c46b7
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-factsheet-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-factsheet-7.1.1+20260306.035609.21
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-factsheet-operator-catalog@sha256:2d2d75d4a944ffbf6c09f764ce90730537b85113f82faded7284202a41dc55b0
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-hadoop-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-hadoop-5.3.2+20260323.000000.26
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-hadoop-operator-catalog@sha256:4355199bc8e84cfbb40a011ce32dade56b74594b7961bd5f19c9f5cbdeff37b7
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-scheduling-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cpd-scheduling-1.61.2+20260321.000338.ef94a9bb
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-scheduler-operator-catalog@sha256:76f7c830ac797b52146a58ed9a5c01d8b198de31f8cff95134737aab39e53987
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-spss-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-spss-12.1.2+20260326.161524.7
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-spss-operator-catalog@sha256:3bdbee71738c77ee98619990ef79b021b7ff3e0f40671da1e834d4dce8f82cd4
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-wkc-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-wkc-5.3.11+20260310.170313.1212
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-wkc-operator-catalog@sha256:289cf0c22de881dd38f6ce1ab08fa26c0ee61b2685878608084892fb15d8d37f
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-wml-accelerator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-wml-accelerator-5.0.2+20240806.025513.2052
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-wml-accelerator-operator-catalog@sha256:a0438b0b41510def6d73a7d6ff816f44c43acf55a4d0c58654efe390b3be2ef0
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-wml-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-wml-cpd-12.1.1+20260321.040559.49
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-wml-operator-catalog@sha256:088267069073caf99e63c014db8020dbdac0ec9ca1f5397f385d2dcea854b361
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ws-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-wsl-8.3.0+20240209.173620.31
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-ws-operator-catalog@sha256:dcac02b3a2490536a39cdd91a2771080eaa1839fc433a506c33804b36778fb05
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ws-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-wsl-10.0.0+20241118.190434.66
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-ws-operator-catalog@sha256:b8dfd70da612cb49bbbc909749a59a0dbcbbf7ec9bf9d1d6ea8c541759794400
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-wspipelines-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-ws-pipelines-12.1.2+20260409.081747.9
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-wspipelines-operator-catalog@sha256:1ddb1d7ae60478ba3f58674853c55578dd1888ccd2bd8c8b6f92838f34e0e673
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cs-iam-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cs-iam-4.17.0
  publisher: IBM
  image: icr.io/cpopen/ibm-iam-operator-catalog@sha256:beac2f4e7369a320e4a2eebd938830af0fe8e9c68bde5b0d5427a989441e63ae
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cs-install-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cs-install-4.18.0
  publisher: IBM
  image: icr.io/cpopen/ibm-cs-install-catalog@sha256:99e9d2c387395e31d40fec96c47b1cc7d4610eb3682369ab99d0f211fbd34eca
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-datagate-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-datagate-prod-11.1.2+20260319.144710.108
  publisher: IBM
  image: icr.io/cpopen/ibm-datagate-operator-catalog@sha256:b83548f0a97bc09f1108672765a1dd555e7f03529564a359c905a7cb15c6bf3d
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-db2aaservice-cp4d-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-db2aaservice-5.3.2+20260310.172818.3717.5005
  publisher: IBM
  image: icr.io/cpopen/ibm-db2aaservice-cp4d-operator-catalog@sha256:b4744be4a9244b0579df62dcf981175208115fc46d8768817d8a7ba73c6667d9
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-db2uoperator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-db2uoperator-7.6.0+20260224.123157.19264
  publisher: IBM
  image: icr.io/cpopen/ibm-db2uoperator-catalog@sha256:f3596edf224621175b5739cf36d7e9b53179816191f9a4123064aedb57e642e9
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-db2uoperator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-db2uoperator-7.6.0+20260224.123157.19264
  publisher: IBM
  image: icr.io/cpopen/ibm-db2uoperator-catalog@sha256:ac608e4f744be84997e0306e459f086a99223749bc29725045e3f673b1c0446b
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-db2uoperator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-db2uoperator-5.0.0
  publisher: IBM
  image: icr.io/cpopen/ibm-db2uoperator-catalog@sha256:aae7c71dce4e7b1859183750764aac564f6f9fdfdb346a104701a1286d6f0c9b
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-db2uoperator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-db2uoperator-5.0.0
  publisher: IBM
  image: icr.io/cpopen/ibm-db2uoperator-catalog@sha256:d8b79c87951e3c6659a5901f8e85136cc803b8553e7c05e77a1031704906519b
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-db2uoperator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-db2uoperator-6.0.3+20241012.145531.11278
  publisher: IBM
  image: icr.io/cpopen/ibm-db2uoperator-catalog@sha256:3325c4e4ec118c186f80b8336e5a3a5d8e2c2d7a1f06d97c9fee1cc4c90d68dc
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-db2uoperator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-db2uoperator-6.0.3+20241012.145531.11278
  publisher: IBM
  image: icr.io/cpopen/ibm-db2uoperator-catalog@sha256:3d8a379ecc97328eee2e4d5c83f380c87f1b5a32c4097112116f24f287226830
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-db2wh-cp4d-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-db2wh-5.3.2+20260310.172818.3717.5005
  publisher: IBM
  image: icr.io/cpopen/ibm-db2wh-cp4d-operator-catalog@sha256:2e770c62678ee600d8d3bbca855c9998b51c444ff3a1d473611e184555ee6f72
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-dmc-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-dmc-8.11.0+20260219.003835.32
  publisher: IBM
  image: icr.io/cpopen/ibm-dmc-operator-catalog@sha256:00de819d3205613a85dc8a4322227c5f11254936b89458889ef7a1ccd5bbd498
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-elasticsearch-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-elasticsearch-operator-1.1.2667
  publisher: IBM
  image: icr.io/cpopen/opencontent-elasticsearch-operator-catalog@sha256:a34169228887ff93161584753c990bb82a5520ad7945dfa1ff4078e70aede592
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-events-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-events-operator-5.2.1
  publisher: IBM
  image: icr.io/cpopen/ibm-events-operator-catalog@sha256:228ea92d69daa2350e151d1fe6b14e6fb56eadd0d3b5b5872178180747297687
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-openscale-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-watson-openscale-10.1.2+20260323.234919.30
  publisher: IBM
  image: icr.io/cpopen/ibm-watson-openscale-operator-catalog@sha256:44b6a3ce38b29533fc5be372ae8bee11697dd9e77d6bc02666f2046d17432e03
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-opensearch-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-opensearch-operator-1.2.0
  publisher: IBM
  image: icr.io/cpopen/opencontent-ibm-opensearch-operator-catalog@sha256:c20414136174ef24513560ca56204787fb4a3c3de8f84a490551dd63efb67a7f
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-rabbitmq-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-rabbitmq-operator-1.0.57+20250909.172851
  publisher: IBM
  image: icr.io/cpopen/opencontent-rabbitmq-operator-catalog@sha256:05fc303da5adf8f8dc67a432849d46341be900ef8a782432cfefd8a9c3df1f8d
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-redis-cp-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-redis-cp-1.3.1+20260209.171809.004
  publisher: IBM
  image: icr.io/cpopen/ibm-redis-cp-operator-catalog@sha256:33aa607160683e22e89c86a81d59eb9c4a6e4b6cb85ab2825a78ece7f36ea194
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-redis-cp-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-redis-cp-1.1.4
  publisher: IBM
  image: icr.io/cpopen/ibm-redis-cp-operator-catalog@sha256:1e81cab5cf1f3e44527e8a893f6648c106b13c6df78b7abbe70993925e63033d
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: opencloud-operators
  namespace: openshift-marketplace
spec:
  displayName: ibm-cp-common-services-4.18.0
  publisher: IBM
  image: icr.io/cpopen/ibm-common-service-catalog@sha256:37bfaf01968c8b14982a1151db90c48aa83bcbfbcf4183052b6b828a068a94ae
  sourceType: grpc
