apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ccs-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-ccs-13.0.1+20260611.163504.84
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-ccs-operator-catalog@sha256:6481124f7d6188a5986e2df971171dc60b58517a2ff2ef30531110af2a714882
  sourceType: grpc
