apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ucda-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-ucda-case-1.4.33-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ucda-operator-catalog@sha256:070ec582360bb3393bef1e0d24b3d3d0e8f5d38919d0d551df116fed3743b526
  sourceType: grpc
  grpcPodConfig:
    nodeSelector:
      kubernetes.io/arch: amd64
