kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: icr.io/cpopen/di-operator:5.4.2-2@sha256:bfd02c2046d09f434c2a3ce0c654983dd022732942224a1d23230db7d9b631e4
