apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cloud-native-postgresql-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cloud-native-postgresql-5.40.0+20260511.071333.2716
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog@sha256:563e0032a3d96e39a7f94cc1bcd4fea5ec38d6249da591baaec1473cf58cf7a9
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ccs-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-ccs-11.2.0+20251022.124506.190
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-ccs-operator-catalog@sha256:3dde1eeb2c132e914ff4d308766eeb50d5c96c569953b5c60b406ca79ad906a9
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ccs-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-ccs-13.0.2+20260624.143147.50
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-ccs-operator-catalog@sha256:d74d1489d8b98db544b8bd521728193a12cdde938572f970effaaf8a903e190c
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-opensearch-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-opensearch-operator-1.1.4009
  publisher: IBM
  image: icr.io/cpopen/opencontent-ibm-opensearch-operator-catalog@sha256:978763bcea32db8e03928870cbe0b7352f3910b031013f28c74272303cacccf5
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-opensearch-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-opensearch-operator-1.4.3
  publisher: IBM
  image: icr.io/cpopen/opencontent-ibm-opensearch-operator-catalog@sha256:4a40ac23337e129531396e2e59bc00f65f25b8b70d52a190d4c116135ff39267
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-watsonx-ai-ifm-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-watsonx-ai-ifm-11.2.0+20251020.191009.184
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-watsonx-ai-ifm-operator-catalog@sha256:01dbd10e252ca5fbe85ebbe62760e8b65cd622c7856cb93f576e89863f31f3b7
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-watsonx-data-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-watsonx-data-6.0.0+20251212.182616.148
  publisher: IBM
  image: icr.io/cpopen/ibm-lakehouse-operator-catalog@sha256:c26c49ec888fd8920a9a1ce034e2a6e49d88fb28476f99c26089c22ec392175f
  sourceType: grpc
