kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-ssp-engine/ssp-engine-docker-image:6.2.1.2-iFix02-2026-05-25@sha256:7beee5d45b0358450ab2bad6badba202a48540ca5ba14553660b0427f698f5ec
