kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: icr.io/cpopen/ibmcloud-object-storage-driver:1.9.16@sha256:a4e05dae476346dff93c7f3375e2190786513acfb81a484b0ffcad674f64b2c1
  - name: icr.io/cpopen/ibmcloud-object-storage-plugin:1.9.16@sha256:aa0fa7abcdc48d9791745cff06425f4f5b2bcbd299f960a24c4fab25be20a9f2
