apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: bts-operator
  namespace: openshift-marketplace
spec:
  displayName: ibm-bts-bundle-1.0.39
  publisher: IBM
  image: icr.io/cpopen/ibm-bts-operator-catalog@sha256:25458e158903b6645f17f3b2ec076f60a595872680cc6b8cdca596434239c4b7
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-ba-insights-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-ba-insights-26.0.2
  publisher: IBM
  image: icr.io/cpopen/ibm-bai-catalog@sha256:5221387ea6ddbe64b86666958527fcfe3894e6dc01f09ad4ec12d100a8bde623
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cs-flink-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cs-flink-2.0.20+20260812.100000
  publisher: IBM
  image: icr.io/cpopen/ibm-opencontent-flink-operator-catalog@sha256:213ad9bbb57059ecea1bad90f9d433f8402d7040805d30ea32947e666d29cbcc
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cs-install-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cs-install-4.19.2+20260819.100000
  publisher: IBM
  image: icr.io/cpopen/ibm-cs-install-catalog@sha256:7e04eb94c33ca06ce1144a5b2ef5cd6bb53ed24b15e68c9414d284826468f9a4
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-opensearch-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-opensearch-operator-1.4.5
  publisher: IBM
  image: icr.io/cpopen/opencontent-ibm-opensearch-operator-catalog@sha256:001157d4e2a80a96b507c3c9b7ec3d17a8149b269db40f334c89d33398803072
  sourceType: grpc
