apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-3.2.23
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:c67ad70227cc1fd6a51031904a33cfa8d84ae671ef432ebd6561d2573ca0a81c
  sourceType: grpc
