apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ae-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-analyticsengine-12.1.13+20260821.033702.2692
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-analyticsengine-operator-catalog@sha256:fcc1c60817d0e13e96bccd54e57e9ea46c1c171115304a6a2c2ad7a68cd3c480
  sourceType: grpc
