apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cloud-native-postgresql-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cloud-native-postgresql-5.40.0+20260511.071333.2716
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog@sha256:563e0032a3d96e39a7f94cc1bcd4fea5ec38d6249da591baaec1473cf58cf7a9
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cs-iam-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cs-iam-4.5.19
  publisher: IBM
  image: icr.io/cpopen/ibm-iam-operator-catalog@sha256:f8c4ba1862a1185b9bdd08737af7537753070f62c2a861235caae93ab2f8830d
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cs-install-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cs-install-4.6.22
  publisher: IBM
  image: icr.io/cpopen/ibm-cs-install-catalog@sha256:ae3fd1dd0f21b10f6c4c80f2089b4476dc1c858abeb9dd31073a428ddb32d38a
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-events-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-events-operator-5.2.1
  publisher: IBM
  image: icr.io/cpopen/ibm-events-operator-catalog@sha256:228ea92d69daa2350e151d1fe6b14e6fb56eadd0d3b5b5872178180747297687
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-zen-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-zen-3.1.22
  publisher: IBM
  image: icr.io/cpopen/ibm-zen-operator-catalog@sha256:cdbfa293c4c6f6428bec1e9dc4e3180653b98004b0f69bbfd15ebf61b088720c
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: opencloud-operators
  namespace: openshift-marketplace
spec:
  displayName: ibm-cp-common-services-4.6.22+20260812.100000
  publisher: IBM
  image: icr.io/cpopen/ibm-common-service-catalog@sha256:8f985635cf086ca7727b42c1b6cbe81e64e843a15133309bfa0e0291daae2a72
  sourceType: grpc
