kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-ssp-ps/ssp-ps-docker-image:6.1.0.5-iFixGA-2026-09-15@sha256:b277840a424bb5cd566c80418e0a0b0e28af0d3c262bfb06ba2c663c4f7f24f5
