apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cs-flink-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cs-flink-2.0.20
  publisher: IBM
  image: icr.io/cpopen/ibm-opencontent-flink-operator-catalog@sha256:7bd7ec7afe332707a826a7e3634d380cc9574bdf18d0467cfbdb0ae1c4e384a5
  sourceType: grpc
