kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-connectdirect/cdu:6.3.0.7-iFix000-2026-02-23@sha256:b70c097b3b467850d039d8c5299c5ea52eb84feafdd432992d4b076bd347eb38
