apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-watsonx-data-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-watsonx-data-7.0.0+20260527.102706.221
  publisher: IBM
  image: icr.io/cpopen/ibm-lakehouse-operator-catalog@sha256:b1d928fb757a4bdea720c29adf8b48240ee685fdf120e18c649fb72a73940bf3
  sourceType: grpc
