apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ccs-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-ccs-12.1.1+20260312.012535.47
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-ccs-operator-catalog@sha256:f70f047e93d6f7bb77f638e5eb6a996895e0b50d5bab05094459fdaab7110c52
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-wspipelines-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-ws-pipelines-12.1.2+20260409.081747.9
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-wspipelines-operator-catalog@sha256:1ddb1d7ae60478ba3f58674853c55578dd1888ccd2bd8c8b6f92838f34e0e673
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-opensearch-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-opensearch-operator-1.2.0
  publisher: IBM
  image: icr.io/cpopen/opencontent-ibm-opensearch-operator-catalog@sha256:c20414136174ef24513560ca56204787fb4a3c3de8f84a490551dd63efb67a7f
  sourceType: grpc
