apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ccs-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-ccs-12.1.6+20260520.232601.47
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-ccs-operator-catalog@sha256:bdfec41fee316c05970145e1b3fd1f1295e4f5c027717d04b985cc57f3bea845
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-opensearch-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-opensearch-operator-1.4.1
  publisher: IBM
  image: icr.io/cpopen/opencontent-ibm-opensearch-operator-catalog@sha256:17e6f19f43ae3f83ea8fddcd81d0b7cf42ec1e5b94ab353fdc3249679b24dcad
  sourceType: grpc
