kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  additionalImages:
  - name: cp.icr.io/cp/ibm-cdws/cdws:6.3.0.20_iFix00-2026-07-10@sha256:bfe7b8be7433872f7249cfcd670de3f572bc415e24e88ab16e287fcfdebd1c5a
