apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-zen-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-zen-6.4.3+20260406.145326.4
  publisher: IBM
  image: icr.io/cpopen/ibm-zen-operator-catalog@sha256:8ae081aae4a110d6583321289139b04bf64de1f55586172fc864b44920f8a5df
  sourceType: grpc
