apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-zen-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-zen-3.1.21
  publisher: IBM
  image: icr.io/cpopen/ibm-zen-operator-catalog@sha256:29e3f98c94feb364927eb5d79ceb5cdcd0ac92f980bc77bfdfc0c2b1b0fc6f1c
  sourceType: grpc
